### ISSUE TITLE
Can't get BaseStation data on port 30003

### ISSUE THREAD

**Issue by luciodaou** [mikenye/docker-readsb#29]
Hello, I installed readsb dockers as described but can't get BaseStation data on port 30003 with nc command:
`nc localhost 30003.`

I noticed that the ports section of readsb on docker-compose.yml file only had ports 80 and 30005 explicitly listed. Adding 30003:30003 and restarting the docker and the computer there made no difference at all.

Am I doing something wrong?

**Comment by mikenye** [comment]
Try adding `--net-sbs-port=30003` to your command line, as well asmapping port `30003`.

For example:

```
docker run \
 -d \
 --rm \
 --name readsb \
 --device /dev/bus/usb/001/004 \
 -p 8080:8080 \
 -p 30003:30003 \
 -p 30005:30005 \
 -e TZ=Australia/Perth \
 mikenye/readsb \
 --dcfilter \
 --device-type=rtlsdr \
 --fix \
 --json-location-accuracy=2 \
 --lat=-33.33333 \
 --lon=111.11111 \
 --modeac \
 --ppm=0 \
 --net \
 --stats-every=3600 \
 --quiet \
 --write-json=/run/readsb \
 --net-sbs-port=30003
```

**Comment by luciodaou** [comment]
I'm using the docker-compose method. So making the proper adjustments it is now like this:
```
  readsb:
    image: mikenye/readsb:latest
    tty: true
    container_name: readsb
    restart: always
    devices:
      - /dev/bus/usb/001/004:/dev/bus/usb/001/004
    ports:
      - 8080:8080
      - 30003:30003
      - 30005:30005
    networks:
      - adsbnet
    environment:
      - TZ=UTC
    command:
      - --dcfilter
      - --device-type=rtlsdr
      - --json-location-accuracy=2
      - --lat=xxxxxxxx
      - --lon=xxxxxx
      - --modeac
      - --ppm=0
      - --net
      - --stats-every=3600
      - --quiet
      - --write-json=/run/readsb
      - --net-sbs-port=30003
```

But netcat on localhost 30003 still doesn't work, but using the readsb docker ip works:
```
pi in /opt/adsb at raspberrypi
nc localhost 30003
pi in /opt/adsb at raspberrypi
nc 172.18.0.5 30003

MSG,4,1,1,XXXXXX,1,2020/11/27,18:13:09.003,2020/11/27,18:13:09.003,,,358,201,,,-1664,,,,,0
```

The `docker ps` command gives me following result:
```
CONTAINER ID       ...  PORTS                                                                                NAMES
ad817c3feaeb       ...  80/tcp, 30003/tcp, 30005/tcp, 30105/tcp, 30978-30979/tcp, 0.0.0.0:8081->8080/tcp     piaware
b4b16b993125       ...  30003/tcp, 0.0.0.0:8754->8754/tcp, 30334/tcp                                         fr24
b744036e7843       ...  30105/tcp, 32088/tcp                                                                 rbfeeder
ab73c36bd7bc       ...  0.0.0.0:30053->30053/tcp, 30054/tcp                                                  pfclient
20b0acbd0117       ...  0.0.0.0:8079->80/tcp                                                                 graphs1090
3eb4295df76f       ...                                                                                       opensky
a6aa66448f1c       ...  0.0.0.0:8078->80/tcp                                                                 tar1090
5e49eff3477a       ...                                                                                       adsbx
f73015f31e88       ...  0.0.0.0:8080->8080/tcp, 30001-30004/tcp, 0.0.0.0:30005->30005/tcp, 30104-30105/tcp   readsb
```
