### ISSUE TITLE
Not receiving messages with Readsb vs Dump1090-fa

### ISSUE THREAD

**Issue by Guzbikes** [mikenye/docker-readsb#3]
I have my "full stack" setup running on a Raspberry Pi4 using Docker compose, and I am receiving messages when I use a Dump1090 container. However, when stop the Dump1090 container and switch to this Readsb container, I am getting 0 messages, even though it seems to be seeing the RTL SDR just fine. 

Here is the startup log of the container:

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.

[s6-init] ensuring user provided files have correct perms...exited 0.

[fix-attrs.d] applying ownership & permissions fixes...

[fix-attrs.d] done.

[cont-init.d] executing container initialization scripts...

[cont-init.d] done.

[services.d] starting services

[services.d] done.

Sat Apr 25 19:49:59 2020 UTC  Mictronics v3.8.2 starting up.

rtlsdr: using device #0: Generic RTL2832U OEM (Realtek, RTL2838UHIDIR, SN 00000001)

Found Rafael Micro R820T tuner

rtlsdr: tuner gain set to 49.6 dB

Allocating 16 zero-copy buffers
```

Is it possible I need different settings for my RTL SDR? I have the NooElec Nesdr Mini 2+ 

Here is the relevant section of docker-compose.yml:

```
  readsb:
    image: mikenye/readsb:latest
    tty: true
    container_name: readsb
    restart: always
    devices:
      - /dev/bus/usb/001/003:/dev/bus/usb/001/003
    ports:
      - 8080:80
      - 30005:30005
      - 30003:30003
    networks:
      - adsbnet
    volumes:
      - readsbjsondata:/var/run/readsb
    command:
      - --dcfilter
      - --device-type=rtlsdr
      - --fix
      - --forward-mlat
      - --json-location-accuracy=2
      - --lat=33.00000
      - --lon=-111.00000
      - --mlat
      - --modeac
      - --ppm=0
      - --net
      - --stats-every=3600
      - --quiet
      - --write-json=/var/run/readsb
```
