### ISSUE TITLE
[HELP] Connect to a FR24 box

### ISSUE THREAD

**Issue by alexbogus** [mikenye/docker-readsb#5]
Hi, 

In order not to have an RTLSDR and a FR24 box, I would like to use the readsb docker container to connect to my FR24 and feed my adsb messages to other platforms or just to see my planes on my own instance of tar1090. 

I'm trying to make my docker-compose.yml passing the the next variables, but  I have errors whe the docker goes up.

```
  readsb:
    image: mikenye/readsb:latest
    tty: true
    container_name: readsb
    restart: always
    ports:
      - 8080:80
      - 30005:30005
    networks:
      - adsbnet
    command:
      - --dcfilter
      - --fix
      - --forward-mlat
      - --json-location-accuracy=2
      - --lat=XX.XXX
      - --lon=XX.XXX
      - --mlat
      - --modeac
      - --stats-every=3600
      - --quiet
      - --write-json=/var/run/readsb
      - --net
      - --net-only
      - --net-connector xx.x.xx.xx, 30334, raw
```
The errors that I haver are:
```
,/usr/local/bin/readsb: unrecognized option '--net-connector xx.xx.xx.xx, 30334, raw'
,Try `readsb --help' or `readsb --usage' for more information.
,[cmd] /usr/local/bin/readsb exited 64
,[cont-finish.d] executing container finish scripts...
,[cont-finish.d] done.
,[s6-finish] waiting for services.
,[s6-finish] sending all processes the TERM signal.
,[s6-finish] sending all processes the KILL signal and exiting.
```
This is the architecture that I would like to deploy, just to explore the possibilities and to tinker with.

![architecture](https://user-images.githubusercontent.com/681181/80749843-62745d00-8b27-11ea-877f-c1b761904e41.png)

Thanks in advance
Kind regards

**Comment by mikenye** [comment]
Hi @alexbogus,

Try this:

```
  readsb:
    image: mikenye/readsb:latest
    tty: true
    container_name: readsb
    restart: always
    ports:
      - 8080:80
      - 30005:30005
    networks:
      - adsbnet
    command:
      - --dcfilter
      - --fix
      - --forward-mlat
      - --json-location-accuracy=2
      - --lat=XX.XXX
      - --lon=XX.XXX
      - --mlat
      - --modeac
      - --stats-every=3600
      - --quiet
      - --write-json=/var/run/readsb
      - --net
      - --net-only
      - --net-connector=x.x.x.x,30334,raw_in
```

The `--net-connector` argument syntax is as follows:

```
--net-connector=<ip,port,protocol>
Establish connection, can be specified multiple times (e.g. 127.0.0.1,23004,beast_out)
Protocols: beast_out, beast_in, raw_out, raw_in, sbs_out, vrs_out
```

Let me know if this works.

Kind regards,
Mike Nye
